SRCS=ActivityLog.cpp \
     AddonActivity.cpp \
     AddonManagementActivity.cpp \
     BaseActivity.cpp \
     MediaLibraryActivity.cpp \

LIB=activity.a

include ../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))

